version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: har-analyzer-backend
    restart: unless-stopped
    ports:
      - "8088:8000"
    environment:
      - DATABASE_URL=sqlite:////app/data/har_analyzer.db
      - SECRET_KEY=${SECRET_KEY:-YourSecureSecretKey}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-AnotherSecureSecretKey}
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - DEBUG=False
      - CORS_ORIGINS_STR=http://o80wgcws8cs8cwwko88wwgko.5.78.117.57.sslip.io:3088,http://localhost:3088,http://localhost:3000
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.override
    container_name: har-analyzer-frontend
    restart: unless-stopped
    ports:
      - "3088:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://o80wgcws8cs8cwwko88wwgko.5.78.117.57.sslip.io:8088/api
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  data:
    name: har-analyzer-data

# Uncomment if you want to use PostgreSQL in production
# volumes:
#   postgres_data: 